[build]
  publish = "code/built-storybooks"
  command = "cd scripts && yarn && cd ../code && yarn && yarn bootstrap --core && yarn build-storybooks --all"
[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.22.10"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
